import os
import json

def export_to_markdown(json_path: str = "./outputs/topic_index.json", output_md_path: str = "./outputs/topic_index_report.md"):
    """Reads the JSON topic index and exports a human-readable Markdown report for attorneys."""
    if not os.path.exists(json_path):
        raise FileNotFoundError(f"Topic index JSON not found at {json_path}. Run segmenter.py first.")

    with open(json_path, "r", encoding="utf-8") as f:
        topics = json.load(f)

    md_lines = [
        "# DepoIndex: AI-Powered Deposition Topic Index",
        "**Deposition of:** Persis Yu  \n**Generated by:** Docu3C AI Deposition Indexing Engine\n",
        "---",
        "## Chronological Topic Index\n",
        "| Topic | Start Location | End Location | Supporting Evidence / Source Reference |",
        "| :--- | :--- | :--- | :--- |"
    ]

    for item in topics:
        topic = item["topic"]
        start = item["start_location"]
        end = item["end_location"]
        evidence = item["supporting_evidence"].replace("\n", " ")
        md_lines.append(f"| **{topic}** | {start} | {end} | `{evidence}` |")

    md_lines.extend([
        "\n---",
        "## Verification & Provenance Notes",
        "- Every entry maps directly to extracted text chunks from the vector store.",
        "- Page and line references correspond to official deposition transcript pagination.",
        "- Attorneys can cross-reference the supporting snippet directly against the primary PDF source."
    ])

    os.makedirs(os.path.dirname(output_md_path), exist_ok=True)
    with open(output_md_path, "w", encoding="utf-8") as f:
        f.write("\n".join(md_lines))

    print(f"Human-readable Markdown report successfully exported to {output_md_path}!")

if __name__ == "__main__":
    export_to_markdown()  