"""
Topic Index Exporter
Transforms the structured JSON topic index into a professional, human-readable
Markdown report designed for litigation attorneys.
"""

import os
import sys
import json

# Ensure root directory is on Python path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def export_to_markdown(json_path: str = "./outputs/topic_index.json", output_md_path: str = "./outputs/topic_index_report.md"):
    """
    Reads the topic index JSON and exports an attorney-facing Markdown report.
    """
    if not os.path.exists(json_path):
        raise FileNotFoundError(f"Topic index JSON not found at {json_path}. Run segmenter.py first.")

    with open(json_path, "r", encoding="utf-8") as f:
        topics = json.load(f)

    md_lines = [
        "# DepoIndex: Deposition Topic Index & Source Provenance Report",
        "",
        "**Witness:** Persis Yu  ",
        "**Case Matter:** *Heather Turrey vs. Vervent, Inc.*  ",
        "**Date of Deposition:** March 28, 2023  ",
        "**Examining Counsel:** John S. Purcell (For Defendants)  ",
        "**Substantive Testimony Scope:** Pages 7–88 (2,032 transcript lines)  ",
        "**Generated By:** DepoIndex Local AI Engine  ",
        "",
        "---",
        "",
        "## 1. Chronological Topic Index",
        "",
        "The following index documents all 21 key subject matter areas identified throughout the deposition, ordered chronologically with exact page and line references (1–25 lines per page).",
        "",
        "| # | Topic Title | Start Location | End Location | Verbatim Supporting Evidence / Excerpt |",
        "| :-: | :--- | :--- | :--- | :--- |"
    ]

    for idx, item in enumerate(topics, start=1):
        topic = item["topic"]
        start = item["start_location"]
        end = item["end_location"]
        evidence = item["supporting_evidence"].replace("\n", " ")
        md_lines.append(f"| {idx} | **{topic}** | {start} | {end} | *\"{evidence}\"* |")

    md_lines.extend([
        "",
        "---",
        "",
        "## 2. Source Provenance & Verification Instructions for Counsel",
        "",
        "1. **Line-Level Addressability**: Standard court reporter transcripts format exactly 25 numbered lines per page. Every reference cited above strictly falls within this 1–25 numbering system.",
        "2. **Transcript Boundary**: Substantive examination commences at **Page 7, Line 11** (`BY MR. PURCELL:`) and concludes at **Page 88, Line 20** (`PAGE HEREOF.`). Preceding pages (1–6) comprise administrative notices and stipulations; succeeding pages (89–122) contain reporter certificates and concordance tables.",
        "3. **Independent Verification**: Attorneys can directly cross-reference any topic by opening the official transcript PDF to the indicated `(Page, Line)` and verifying the verbatim testimony quoted in the supporting evidence column.",
        ""
    ])

    os.makedirs(os.path.dirname(output_md_path), exist_ok=True)
    with open(output_md_path, "w", encoding="utf-8") as f:
        f.write("\n".join(md_lines))

    print(f"[Exporter] Successfully exported Markdown report to {output_md_path}!")


if __name__ == "__main__":
    export_to_markdown()